# Generated by Django 4.2.11 on 2024-06-10 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("_datetimeAdded", models.DateTimeField(auto_now=True)),
                ("_datetimeChanged", models.DateTimeField(auto_now_add=True)),
                ("first_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("birthdate", models.DateField()),
                ("emails", models.EmailField(max_length=254)),
                ("phones", models.CharField(editable=False, max_length=200)),
                ("discord", models.CharField(max_length=37)),
                ("steam", models.CharField(max_length=32)),
                ("battlenet", models.CharField(max_length=32)),
                ("instagram", models.CharField(max_length=32)),
                ("facebook", models.CharField(max_length=32)),
                ("github", models.CharField(max_length=32)),
                ("leagueoflegends", models.CharField(max_length=32)),
            ],
        ),
    ]
